name: Update PoE Ladder

on:
  schedule:
    - cron: '0 * * * *' # Odpalaj co pełną godzinę
  workflow_dispatch: # Pozwala odpalić ręcznie przyciskiem

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas playwright lxml beautifulsoup4
          playwright install chromium

      - name: Run script
        run: python update_ladder.py

      - name: Upload Debug Screenshot
        if: always() # To sprawi, że wyśle screena nawet jak będzie błąd
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: data/*.png

    - name: Commit and push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/keepers-delve.tsv
        git commit -m "Update ladder data" || echo "No changes to commit"
        git push
