name: Update PoE Ladder

on:
# schedule:
#   - cron: '0 */6 * * *'  # Automat tymczasowo wyłączony
  workflow_dispatch:        # Pozwala na ręczne uruchomienie przyciskiem

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Wait for random time
        # GitHub Actions czasami blokuje przez idealną punktualność. 
        # Ten krok poczeka od 1 do 60 sekund przed startem.
        run: sleep $((1 + RANDOM % 60))

      - name: Install dependencies
        run: |
          pip install pandas playwright lxml beautifulsoup4
          playwright install --with-deps chromium

      - name: Run scraper
        run: python update_ladder.py

      - name: Upload Debug Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: data/*.png
          if-no-files-found: ignore

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/keepers-delve.tsv
          git commit -m "Update ladder data" || echo "No changes to commit"
          git push
